name:               krop
version:            0.4.13.1
summary:            A tool to crop PDF files
description:        |
  krop is a simple graphical tool to crop the pages of PDF files.
  It is written in Python and relies on PyQT, python-poppler-qt and pyPDF for
  its functionality. A unique feature of krop is its ability to automatically
  split pages into subpages to fit the limited screen size of devices such as
  eReaders. This is particularly useful, if your eReader does not support
  convenient scrolling.

grade:              stable
confinement:        strict
type:               app

apps:
  krop:
    command:        desktop-launch krop
    plugs:
      - unity7
      - home
      - removable-media
      - browser-support
      - x11
      - gsettings

parts:
  krop-app:
    plugin:       python
    python-version: python3
    stage-packages:
      - python3-sip
      - python3-poppler-qt5
      - python3-pypdf2
      - python3-pyqt5 # needed

      # FIXME:    check if those packages are needed.
      - xcursor-themes
      - fonts-liberation
      - libqt5gui5
      - libqt5core5a

      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info

      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - xdg-utils  # https://www.freedesktop.org/wiki/Software/xdg-utils/

      - libgail-common
      - libatk-adaptor
      - unity-gtk-module-common

    after:        [desktop-qt5]
