name:               krop
version:            0.4.13
summary:            A tool to crop PDF files
description:        |
  krop is a simple graphical tool to crop the pages of PDF files. It is written in Python and relies on PyQT, python-poppler-qt4 and pyPDF for its functionality. A unique feature of krop is its ability to automatically split pages into subpages to fit the limited screen size of devices such as eReaders. This is particularly useful, if your eReader does not support convenient scrolling.

grade:              stable
architectures:      [amd64]
confinement:  strict

apps:
  krop-app:
    command:  krop
    plugs: [unity7, home, removable-media, browser-support, x11]

parts:
  krop-app:
    plugin:         python
    python-version: python3
    stage-packages:
      - python3-poppler-qt4
      - python3-pypdf2
      - python3-pyqt4
      - libc-bin
      - locales
      - ubuntu-ui-toolkit-theme
